config/routes.rb
Rails.application.routes.draw do
  root :to => 'site#root'

  resources :users, only: [:create, :new]
  get '/tour', to: 'users#tour'
  resource :session, only: [:create, :destroy, :new]

  namespace :api, defaults: { format: :json } do
    get 'bikes/search', to: 'bikes#search'
    resources :bikes, only: [:index, :show]
    resources :bike_rental_requests, only: [:index, :show, :create, :destroy]
  end
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  validates(
    :owner,
    :image_url,
    :lat,
    :lng,
    :make,
    :model,
    :year,
    :day_rate,
    :hour_rate,
    presence: true
  )

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :rental_requests, class_name: 'BikeRentalRequest'
end

app/models/bike_rental_request.rb
class BikeRentalRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :bike

  after_initialize :assign_pending_status

  validates(
    :bike,
    :user,
    :start_date,
    :start_time,
    :end_date,
    :end_time,
    :status,
    presence: true
  )

  # validate :does_not_overlap_approved_request

  def pending?
      self.status == "PENDING"
    end


  def does_not_overlap_approved_request
   return if self.denied?

   unless overlapping_approved_requests.empty?
     errors[:base] <<
       "Request conflicts with existing approved request"
   end
 end

 private
  def assign_pending_status
    self.status ||= "PENDING"
  end

  def overlapping_requests
    BikeRentalRequest
     .where("(:id IS NULL) OR (id != :id)", id: self.id)
     .where(bike_id: bike_id)
     .where(<<-SQL, start_date: start_date, end_date: end_date)
      NOT( (start_date > :end_date) OR (end_date < :start_date) )
    SQL
  end

 def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :bikes, foreign_key: :owner_id
  has_many :rental_requests, class_name: 'BikeRentalRequest'

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/bike_rental_requests_controller.rb
class Api::BikeRentalRequestsController < ApplicationController
  def index
    @rentals = current_user.rental_requests.includes(:bike)
    render :show
  end

  def show
    @rental = BikeRentalRequest.find(params['id'])
    render json: @rental
  end

  def create
    @rental = BikeRentalRequest.new(rental_params)

    if @rental.save
      render json: @rental
    else
      render json: @rental.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @rental = BikeRentalRequest.find(params['id'])
    @rental.destroy
    render json: {}
  end


  private
  def rental_params
    params.require(:rental).permit(
      :bike_id,
      :user_id,
      :start_date,
      :start_time,
      :end_date,
      :end_time
    )
  end
end

app/controllers/api/bikes_controller.rb
class Api::BikesController < ApplicationController
  def index
    @bikes = Bike.all
    render json: @bikes
  end

  def show
    @bike = Bike.find(params['id'])
    render :show
  end

  def search
    @bikes = filter_bikes(filter_options)

    render json: @bikes
  end

  private
  def bike_params
    params.require(:bike).permit(:model, :make, :lat, :lng);
  end

  def filter_bikes(filter_data)
    binds = {
      lat_min: filter_data['lat'][0],
      lat_max: filter_data['lat'][1],
      lng_min: filter_data['lng'][0],
      lng_max: filter_data['lng'][1],
      start_date: filter_data['start_date'],
      start_time: filter_data['start_time'],
      end_date: filter_data['end_date'],
      end_time: filter_data['end_time']
    }

    bikes = find_available_bikes(binds)
  end

  def find_available_bikes(binds)
    requests = BikeRentalRequest.where.not(<<-SQL, binds)
      ( (start_date > :end_date) OR (end_date < :start_date) )
    SQL
    binds[:ids] = requests.map{|request| request.bike_id}.uniq

    find_bikes_in_view(binds)
  end

  def find_bikes_in_view(binds)
    if binds[:lng_min].to_f > binds[:lng_max].to_f
      in_view_bikes = Bike.where.not(id: binds[:ids]).where(<<-SQL, binds)
        bikes.lng BETWEEN :lng_min AND 180
          OR bikes.lng BETWEEN -180 AND :lng_max
      SQL
    else
      in_view_bikes = Bike.where.not(id: binds[:ids]).where(<<-SQL, binds)
        bikes.lat BETWEEN :lat_min AND :lat_max
          AND bikes.lng BETWEEN :lng_min AND :lng_max
      SQL
    end
  end

  def filter_options
    options = params[:filter_data] || {}
    defaults = {
      'lat' => [37.67767358309138, 37.8887756788066],
      'lng' => [-122.56501542968749, -122.26838457031249]
    }

    defaults.merge(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email / password"]
      render :new
    end
  end

  def destroy
    sign_out
    render json: {}
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :require_signed_in!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def tour
      render :tour
  end

  private
  def user_params
    params.require(:user).permit(:password, :email, :fname, :lname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/bike_rental_requests_helper.rb
module BikeRentalRequestsHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <% if Rails.env.production? %>
    <% api_key = ENV['google_map_api'] %>
  <% else %>
    <% api_key = '' %>
  <% end %>

  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/yeti/bootstrap.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript" charset="utf-8"></script>

  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css">

  <% if current_user %>
    <script type="text/javascript"> window.currentUser = "<%= current_user.fname %>"</script>
    <script type="text/javascript"> window.currentUserId = "<%= current_user.id %>"</script>
    <script type="text/javascript"> window.cloud_name = "<%= ENV["cloudinary_api"] %>"</script>
    <script type="text/javascript"> window.upload_preset = "<%= ENV["upload_preset"] %>"</script>
  <% end %>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places,key=<%= api_key %>"></script>
  <title>TakeASpin</title>
  <%= favicon_link_tag 'favicon-spinner.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>

  <%= yield %>
</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle"
      data-toggle="collapse"
      data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/session/new">
      <i class="fa fa-spinner fa-lg"></i>
      <span class="logo-font">Take A Spin</span></a>

  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/tour">How it works <span class="sr-only"></span></a></li>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
     <button type="button" class="close" data-dismiss="alert">
       <span class="sr-only">Close</span></button>
          <%= flash[:errors].join("<br>").html_safe %>
  </div>
<% end %>

app/views/site/root.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <div id="nav"></div>
  <div id="content">
</div>
</body>
</html>

app/views/users/new.html.erb
<%= render "shared/header" %>

<div class="welcome-page">
  <center class="welcome">
  <h2 class="sign-in">Rent great bikes from people nearby</h2>
  <div class="sign-in-form col-md-4 col-md-offset-4">

    <form action="<%= users_url %>" method="post">
      <%= auth_token_input %>
        <div class="row form-inline">
          <input class="sign-input name form-control" type="text" name="user[fname]" value="" placeholder="First name">
          <input class="sign-input name form-control" type="text" name="user[lname]" value="" placeholder="Last name">
        </div>

      <input class="sign-input form-control" type="email" name="user[email]" value="" placeholder="Enter your email">

      <input class="sign-input form-control" type="password" name="user[password]" value="" placeholder="Password">

      <br>

      <input type="submit" value="Sign Up" class="btn sign-in-button">
    </form>
    <%= link_to "Log in", new_session_url, { class: 'switch' } %>
  </div>
  </center>

  <center class="bottom-intro">
    <h1 class="intro-1">Renting has never been easier</h1>
    <h1 class="intro-2">Convenient hourly and daily rentals. Insurance included.</h1>
  </center>
</div>

app/views/users/tour.html.erb
<%= render "shared/header" %>

<div class="jumbotron">
  <center>
    <img src="<%= asset_path('bike-icon.png') %>" />
    <h1><b>It Just Does!</b></h1>
    <a href="/" class="bike-search-rentals-show">Fair enough<br><font size="2">(back to login)</font></a>
  </center>
</div>